version: "3"
services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - mern-network
    volumes:
      - ./backend:/app/backend
    environment:
      - CLIENT=http://localhost:3000
    command: npm start

networks:
  mern-network:
    driver: bridge